### ISSUE TITLE
Not working on automation preview

### ISSUE THREAD

**Issue by jikulopo** [Tagnum-Mods/Advanced-Electrolyzer#1]
![image](https://user-images.githubusercontent.com/61334906/75078842-0aa5ee00-5507-11ea-966b-5c8b1277f1dd.png)
[output_log.txt](https://github.com/Tagnum-Mods/Advanced-Electrolyzer/files/4238412/output_log.txt)
Enabling this mod even by itself is unfortunately causing a mod error

**Comment by TagnumElite** [comment]
I know the problem, I'll release an update once the update goes live.

**Comment by TagnumElite** [comment]
Should be fixed!
