### ISSUE TITLE
Mod crashes with Automation Innovation pack

### ISSUE THREAD

**Issue by Storm-Engineer** [Tagnum-Mods/Advanced-Electrolyzer#2]
The mod crashes with Automation Innovation pack. This is expected because the way Klei handles automation ports changed so every mod adding a building that has automation has to be updated or will crash.

**Comment by TagnumElite** [comment]
Yeah, I updated this on 5 March at 8:11pm SAST. Should have been working by now. I've tested all my builds, nothing is breaking.

**Comment by Storm-Engineer** [comment]
When I made this ticket it still wasn't working, but now I tested and seems good so far. Thank you!

**Comment by TagnumElite** [comment]
No Problem
