### ISSUE TITLE
Buufreak outlog report

### ISSUE THREAD

**Issue by buufreak** [Tagnum-Mods/Advanced-Electrolyzer#3]
[output_log.txt](https://github.com/Tagnum-Mods/Advanced-Electrolyzer/files/4314407/output_log.txt)

**Comment by TagnumElite** [comment]
The output log only shows EnableAllModsButtom mod.

**Comment by buufreak** [comment]
[output_log.txt](https://github.com/Tagnum-Mods/Advanced-Electrolyzer/files/4330890/output_log.txt)

Lets try this one. I got it to crash from using the mod, and instead of letting it restart without it I hard closed it. Sorry, I'm not the best with coding and procedures.

**Comment by TagnumElite** [comment]
Yeah, looks like the mod isn't updating for you. Just delete the folder inside your Documents `Klei/OxygenNotIncluded/mods/Steam/1801004057`

**Comment by buufreak** [comment]
That looks to have fixed it. Thanks for the help!
