### ISSUE TITLE
Feature request: Config options

### ISSUE THREAD

**Issue by MISMASJETU** [Tagnum-Mods/Advanced-Electrolyzer#8]
Hi, I have been using this mod for some time I wanted to change few vallues but I have no idea how (don't know how to edit mods) so, maybe you could add feature allowing to set ammount of power, water, oxygen and hydrogen needed, it would really help, I have some small experience with code and I am sure something like this should not be any problem

**Comment by TagnumElite** [comment]
There should be config `config.json` options in the mod folder `Documents\Klei\OxygenNotIncluded\mods\Steam\1801004057`.

**Comment by MISMASJETU** [comment]
> There should be config `config.json` options in the mod folder `Documents\Klei\OxygenNotIncluded\mods\Steam\1801004057`.

Sorry, it was in archived version folder so I ignored it, it could be nice to have acces to this file in-game like some mods does

**Comment by TagnumElite** [comment]
Oh, yeah. I should probably do that.
